language: node_js

node_js:
  - stable

before_install:
  - rvm install 2.3.1

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    - secure: dms/HQglEQyhBk6ukUoPxM+P/ry3RjBX62DehSpvawMKLQoSMBwOv1b+7a6GfIQZZx4shkCx4vpxzwBzNFmDuPsP4jpxdO9qg3CEko1VZk/D81Ghncl5RB3IJj1dyQ8JFj6ubkxtvPoXy+StxYwUi0iybdT1pfgJG8NIwgqe4xo=

before_script:
  - gem install bundler
  - bundle install
  - npm install -g gulp-cli
  - npm install

script:
  - npm run build

after_script:
  - TMP_DIR=$(mktemp -d)
  - GH_REPO=github.com/${TRAVIS_REPO_SLUG}
  - git clone --branch gh-pages git://${GH_REPO} ${TMP_DIR}
  - rm -rf ${TMP_DIR}/*
  - cp -r _site/* ${TMP_DIR}
  - cd ${TMP_DIR}
  - git config user.name "Travis CI"
  - git config user.email "travis-ci@michaelbarrett.io"
  - git add -A .
  - git commit -m "Built from ${TRAVIS_COMMIT}"
  - git push -q "https://${GH_TOKEN}@${GH_REPO}" gh-pages > /dev/null 2>&1
