language: node_js

node_js:
  - 8

before_install:
  - rvm install 2.5.3

sudo: false

branches:
  only:
    - develop

cache:
  yarn: true
  bundler: true
  directories:
    - node_modules

env:
  global:
    - secure: dms/HQglEQyhBk6ukUoPxM+P/ry3RjBX62DehSpvawMKLQoSMBwOv1b+7a6GfIQZZx4shkCx4vpxzwBzNFmDuPsP4jpxdO9qg3CEko1VZk/D81Ghncl5RB3IJj1dyQ8JFj6ubkxtvPoXy+StxYwUi0iybdT1pfgJG8NIwgqe4xo=

before_script:
  - gem install bundler
  - bundle install
  - npm install -g gulp

script:
  - npm run build

after_success:
  - ./scripts/deploy
