# Site settings
title: Michael Barrett - Fullstack Software Engineer
description: Michael Barrett is a Fullstack Software Engineer based in West Yorkshire, UK
url: https://mdb.sh

# Email address
email: mike@mdb.sh

# Disqus settings
disqus_shortname: michaelbarrett-blog

# Gravatar settings
gravatar_username_hash: 730c03c7ecdbd654028b3beb5f592290

# Google analytics settings
google_analytics_site_id: UA-60255036-1

# Social usernames
twitter_username: mike182uk
github_username: mike182uk
lastfm_username: mike182uk
linkedin_username: michaelbarrett88

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [node_modules, gulpfile.coffee, package.json, Gemfile, README.md, yarn.lock, scripts]
plugins :
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect
