#!/usr/bin/env sh

TMP_DIR=$(mktemp -d)
GH_REPO=github.com/${TRAVIS_REPO_SLUG}

git clone --branch master git://${GH_REPO} ${TMP_DIR}

rm -rf ${TMP_DIR}/*
cp -r _site/* ${TMP_DIR}

cd ${TMP_DIR}

git config user.name "Travis CI"
git config user.email "travis-ci@mdb.sh"

git add -A .
git commit -m "Built from ${TRAVIS_COMMIT}"
git push -q "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
